name: Deploy (Production)

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      
      - name: Npm Vet
        run: |-
          npm install
          npm install -g npmvet
          npmvet -r ci

      - name: Lint
        run: |-
          npm install
          npm run lint
      
      - name: Unit Tests
        run: |-
          npm install
          npm run test
      
      - name: Code Coverage
        run: |-
          npm install
          npm run test:cov
      
      - name: Deploy Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cars-api-cognigy"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true